! used to obtain hydraulic variables, dependent on water level but not flowrate
SUBROUTINE GET_HYDRAULIC_VARIABLE(ERROR_RTN, &
                                  MDL_ID, ND_ID, Z, IPRINT, &
                                  B1, B2, BS, P1, P2, S1, S2, RH1, RH2, &
                                  CNVC, BETA)

! declarations ---------------------------------------------------------------------------------------------------------------------
   USE M_APIMASCARET_STATIC
   USE M_MODELE_MASCARET_T
   USE M_ERREUR_T
   USE M_INTERFACE_API_SUBPROGRAM, ONLY : RHSBP_S_API, REPAR_API

   IMPLICIT NONE

   ! inputs
   INTEGER(4),  INTENT(IN) :: MDL_ID, ND_ID
   REAL(8),     INTENT(IN) :: Z
   INTEGER(4),  INTENT(IN) :: IPRINT

   ! outputs
   INTEGER(4), INTENT(OUT) :: ERROR_RTN
   REAL(8),    INTENT(OUT) :: B1, B2, BS, P1, P2, S1, S2, RH1, RH2
   REAL(8),    INTENT(OUT) :: CNVC, BETA

   ! locals
   TYPE(MODELE_MASCARET_T) :: MODEL
   TYPE(ERREUR_T)          :: ERROR

! subroutine codes -----------------------------------------------------------------------------------------------------------------
   MODEL = PTRTABMASCARET(MDL_ID)%MODELEMASCARET

   ERROR%NUMERO = 0
   ERROR%ARBREDAPPEL = 'GET_HYDRAULIC_VARIABLE'
   ERROR_RTN = 0

   CALL RHSBP_S_API(B1, B2, BS, P1, P2, S1, S2, RH1, RH2, &
                    ND_ID, Z, MODEL%ZREF(ND_ID), MODEL%IDT, MODEL%XDT, MODEL%PROFILS, MODEL%PROFILPLAN, &
                    MODEL%FICHIERLISTING%UNITE, ERROR)
   IF (ERROR%NUMERO .NE. 0) THEN
      ERROR_RTN = ERROR%NUMERO
      PTRMSGSERREURS(MDL_ID) = 'GET_HYDRAULIC_VARIABLE - RHSBP_S - '//TRIM(ERROR%MESSAGE)
      IF (IPRINT .NE. 0) THEN
         REWIND(MODEL%FICHIERLISTING%UNITE)
         CLOSE(MODEL%FICHIERLISTING%UNITE)
         IF (MODEL%OPTIONCASIER) CLOSE(MODEL%FICHIERLISTINGCASIER%UNITE)
         IF (MODEL%OPTIONCASIER) CLOSE(MODEL%FICHIERLISTINGLIAISON%UNITE)
         IF (MODEL%OPTIONTRACER) CLOSE(MODEL%TRACER%FICHIERLISTINGTRACER%UNITE)
      ENDIF
      RETURN
   ENDIF

   CALL REPAR_API(CNVC, BETA, &
                  S1, S2, RH1, RH2, &
                  P1, P2, MODEL%CF1(ND_ID), MODEL%CF2(ND_ID), &
                  MODEL%MODELELIT, MODEL%LOIFROTTEMENT, MODEL%PROFILS(MODEL%IDT(ND_ID))%NOM, &
                  ERROR)
   IF (ERROR%NUMERO .NE. 0) THEN
      ERROR_RTN = ERROR%NUMERO
      PTRMSGSERREURS(MDL_ID) = 'GET_HYDRAULIC_VARIABLE - REPAR - '//TRIM(ERROR%MESSAGE)
      IF (IPRINT .NE. 0) THEN
         REWIND(MODEL%FICHIERLISTING%UNITE)
         CLOSE(MODEL%FICHIERLISTING%UNITE)
         IF (MODEL%OPTIONCASIER) CLOSE(MODEL%FICHIERLISTINGCASIER%UNITE)
         IF (MODEL%OPTIONCASIER) CLOSE(MODEL%FICHIERLISTINGLIAISON%UNITE)
         IF (MODEL%OPTIONTRACER) CLOSE(MODEL%TRACER%FICHIERLISTINGTRACER%UNITE)
      ENDIF
      RETURN
   ENDIF

END SUBROUTINE GET_HYDRAULIC_VARIABLE